#!/usr/bin/env bash
#
# End-to-end demo: boots the stack (if needed), starts a local RTMP sink,
# starts the broadcast and drives a fake innings so commentary + TTS fire.
#
# The video is a synthetic clip generated by scripts/make-demo-asset.sh and the
# score events are fake - nothing here touches third-party content.
#
# Usage: bash scripts/demo.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API="${API_URL:-http://127.0.0.1:4000}"
EMAIL="${ADMIN_EMAIL:-admin@matchcast.local}"
PASSWORD="${ADMIN_PASSWORD:-ChangeMeNow123!}"
RTMP_SINK="${RTMP_TEST_URL:-rtmp://127.0.0.1:1935/live/test}"

echo "[demo] MatchCast demo run"
echo "[demo] API: $API"

# ---------------------------------------------------------------- 1. API up?
for _ in $(seq 1 30); do
  if curl -s -f "$API/api/system/health" > /dev/null 2>&1; then break; fi
  sleep 1
done
curl -s -f "$API/api/system/health" > /dev/null || {
  echo "[demo] Backend is not reachable at $API - run 'npm run dev' first." >&2
  exit 1
}

# ------------------------------------------------------- 2. demo video exists
if [ ! -f "$ROOT/demo-assets/demo-match.mp4" ]; then
  echo "[demo] Generating the synthetic demo clip..."
  bash "$ROOT/scripts/make-demo-asset.sh" 60
fi

# ----------------------------------------------------------- 3. local RTMP sink
if ! (exec 3<>/dev/tcp/127.0.0.1/1935) 2> /dev/null; then
  echo "[demo] Starting a local RTMP sink on :1935 (writes .runtime/received.ts)"
  mkdir -p "$ROOT/.runtime"
  nohup bash -c 'while true; do ffmpeg -hide_banner -loglevel error -y -listen 1 -f flv -i rtmp://0.0.0.0:1935/live/test -c copy -f mpegts /home/user/matchcast/.runtime/received.ts; sleep 1; done' \
    > "$ROOT/.runtime/rtmp-sink.log" 2>&1 &
  sleep 2
fi

# ------------------------------------------------------------------- 4. login
TOKEN="$(curl -s -X POST "$API/api/auth/login" \
  -H 'content-type: application/json' \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])')"

# ------------------------------------------------------- 5. pick/create a match
MATCH_ID="$(curl -s "$API/api/matches" -H "authorization: Bearer $TOKEN" \
  | python3 -c 'import sys,json
d=json.load(sys.stdin)
m=d["matches"] if isinstance(d,dict) else d
print(m[0]["id"] if m else "")')"
echo "[demo] Match: ${MATCH_ID:-<none>}"

if [ -n "$MATCH_ID" ]; then
  curl -s -X POST "$API/api/match/$MATCH_ID/start" -H "authorization: Bearer $TOKEN" \
    -H 'content-type: application/json' -d '{}' > /dev/null || true
fi

# ------------------------------------------------------------- 6. go live
echo "[demo] Starting the broadcast -> $RTMP_SINK"
curl -s -X POST "$API/api/stream/start" -H "authorization: Bearer $TOKEN" || true
echo

sleep 8
curl -s "$API/api/stream/status" -H "authorization: Bearer $TOKEN" \
  | python3 -c 'import sys,json
s=json.load(sys.stdin)["status"]
print("[demo] running=%s state=%s fps=%s bitrate=%skbps" % (s["running"], s["state"], s["fps"], s["bitrateKbps"]))'

# ------------------------------------------------------------- 7. fake innings
echo "[demo] Driving deliveries (commentary + TTS should start talking)..."
npx tsx "$ROOT/scripts/demo-scoring.ts" --balls "${DEMO_BALLS:-20}" --delay 2500

echo
echo "[demo] Done. Watch the dashboard, or:"
echo "  ffplay $RTMP_SINK"
echo "  ffplay $ROOT/.runtime/preview/index.m3u8"
echo "[demo] Stop with: curl -X POST $API/api/stream/stop -H 'authorization: Bearer $TOKEN'"
